### PR TITLE
Migrate Tests

### PR DESCRIPTION
**Pull request by jeff-hernandez**
Tests were migrated to GitHub Actions. Branch protection rules should be updated to the new tests.

### CODE REVIEW

**Comment by rwedge** [comment]
Instead of removing the scheduler, what if we updated it to look at github action results?

**Comment by jeff-hernandez** [comment]
I thought we want to separate the scheduler into another PR as we did [here](https://github.com/FeatureLabs/nlp_primitives/pull/46)? Do we want to check whether the latest workflow of a GitHub Action was a success -- similar to [this](https://github.com/FeatureLabs/gh-action-circleci#is_workflow_success)?

**Comment by rwedge** [comment]
The other repo didn't have a scheduler to begin with so it was a slightly different scenario.  I'm fine with dropping the scheduler and adding it back in a separate PR.  I think we should add the github action success check, yes

**Comment by jeff-hernandez** [comment]
Okay sounds good. I'll look into the GitHub Action API for the success check.

**Comment by rwedge** [comment]
Noticed this message in the job output:
```
Using legacy 'setup.py install' for featuretools-tsfresh-primitives, since package 'wheel' is not installed.
```
Can we add steps where we upgrade pip and install `wheel`

**Review by rwedge — APPROVED** [review]
Looks good.  Can you add a quick issue for adding the scheduled check back in?

**Comment by jeff-hernandez** [comment]
Filed as issue #65

**Pull request merged**
